from parser_avito_manager.preparation_links_for_pages import PreparationLinksForPages
from parser_avito_manager.result_in_html import ResultInHtml
from parser_avito_manager.chek_title import CheckTitleMixin
