# -*- coding: utf-8 -*-
from settings import (FONT_SIZE, BACKGROUND_COLOR, FOREGROUND_COLOR,
                      BACKGROUND_COLOR_BTN, FOREGROUND_COLOR_BTN, WIDTH_LABEL, BACKGROUND_COLOR_ENTRY,
                      FOREGROUND_COLOR_ENTRY, COLOR_FOR_HOVER)


class ConfigClass:
    def __init__(self):
        self.FONT_SIZE = FONT_SIZE
        self.BACKGROUND_COLOR = BACKGROUND_COLOR
        self.FOREGROUND_COLOR = FOREGROUND_COLOR
        self.BACKGROUND_COLOR_ENTRY = BACKGROUND_COLOR_ENTRY
        self.FOREGROUND_COLOR_ENTRY = FOREGROUND_COLOR_ENTRY
        self.BACKGROUND_COLOR_BTN = BACKGROUND_COLOR_BTN
        self.FOREGROUND_COLOR_BTN = FOREGROUND_COLOR_BTN
        self.WIDTH_LABEL = WIDTH_LABEL
        self.COLOR_FOR_HOVER = COLOR_FOR_HOVER
