# -*- coding: utf-8 -*-
from settings import (FONT_SIZE, BACKGROUND_COLOR, FOREGROUND_COLOR, BACKGROUND_COLOR_BTN,
                      BACKGROUND_COLOR_ENTRY, FOREGROUND_COLOR_BTN, FOREGROUND_COLOR_ENTRY,
                      WIDTH_LABEL, COLOR_FOR_HOVER)


class ConfigClassMixin:
    """
    Класс использует настройки интерфейса tkinter
    """

    FONT_SIZE = FONT_SIZE
    BACKGROUND_COLOR = BACKGROUND_COLOR
    FOREGROUND_COLOR = FOREGROUND_COLOR
    BACKGROUND_COLOR_ENTRY = BACKGROUND_COLOR_ENTRY
    FOREGROUND_COLOR_ENTRY = FOREGROUND_COLOR_ENTRY
    BACKGROUND_COLOR_BTN = BACKGROUND_COLOR_BTN
    FOREGROUND_COLOR_BTN = FOREGROUND_COLOR_BTN
    WIDTH_LABEL = WIDTH_LABEL
    COLOR_FOR_HOVER = COLOR_FOR_HOVER
